apiVersion: builtin
kind: PatchTransformer
metadata:
  name: clusterrole-syncwave
patch: |-
  apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: "*"
    annotations:
      argocd.argoproj.io/sync-wave: "5"
target:
  kind: ClusterRole
