apiVersion: builtin
kind: PatchTransformer
metadata:
  name: cronjob-syncwave
patch: |-
  apiVersion: batch/v1
  kind: CronJob
  metadata:
    name: "*"
    annotations:
      argocd.argoproj.io/sync-wave: "9"
target:
  kind: CronJob
