apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

transformers:
  - ./namespace-syncwave.yaml
  - ./resourcequota-syncwave.yaml
  - ./storageclass-syncwave.yaml
  - ./customresourcedefinition-syncwave.yaml
  - ./mutatingwebhookconfiguration-syncwave.yaml
  - ./serviceaccount-syncwave.yaml
  - ./podsecuritypolicy-syncwave.yaml
  - ./networkpolicy-syncwave.yaml
  - ./role-syncwave.yaml
  - ./clusterrole-syncwave.yaml
  - ./rolebinding-syncwave.yaml
  - ./clusterrolebinding-syncwave.yaml
  - ./configmap-syncwave.yaml
  - ./secret-syncwave.yaml
  - ./endpoints-syncwave.yaml
  - ./service-syncwave.yaml
  - ./limitrange-syncwave.yaml
  - ./priorityclass-syncwave.yaml
  - ./persistentvolume-syncwave.yaml
  - ./persistentvolumeclaim-syncwave.yaml
  - ./deployment-syncwave.yaml
  - ./statefulset-syncwave.yaml
  - ./cronjob-syncwave.yaml
  - ./poddisruptionbudget-syncwave.yaml
  - ./validatingwebhookconfiguration-syncwave.yaml
