apiVersion: builtin
kind: PatchTransformer
metadata:
  name: resourcequota-syncwave
patch: |-
  apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: "*"
    annotations:
      argocd.argoproj.io/sync-wave: "1"
target:
  kind: ResourceQuota
