apiVersion: builtin
kind: PatchTransformer
metadata:
  name: role-syncwave
patch: |-
  apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: "*"
    annotations:
      argocd.argoproj.io/sync-wave: "5"
target:
  kind: Role
