apiVersion: builtin
kind: PatchTransformer
metadata:
  name: secret-syncwave
patch: |-
  apiVersion: v1
  kind: Secret
  metadata:
    name: "*"
    annotations:
      argocd.argoproj.io/sync-wave: "7"
target:
  kind: Secret
