apiVersion: builtin
kind: PatchTransformer
metadata:
  name: serviceaccount-syncwave
patch: |-
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: "*"
    annotations:
      argocd.argoproj.io/sync-wave: "4"
target:
  kind: ServiceAccount
