apiVersion: builtin
kind: PatchTransformer
metadata:
  name: storageclass-syncwave
patch: |-
  apiVersion: storage.k8s.io/v1
  kind: StorageClass
  metadata:
    name: "*"
    annotations:
      argocd.argoproj.io/sync-wave: "1"
target:
  kind: StorageClass
